# Generated by Django 3.2.3 on 2021-05-29 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paperDetails', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='authors',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='paper',
            name='citation_id',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='paper',
            name='citation_link',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='paper',
            name='link',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='paper',
            name='noOfCitations',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='paper',
            name='publication',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='paper',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
